# Site settings
title: Wac Cards
email: wacath.media@gmail.com
description: "buidling the world's greatest caring network"

# Build settings
markdown: kramdown
permalink: pretty

port: 8000

sass:
   sass_dir: assets/sass
   style: :nested
